version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Achacha
  - ckpt
  - comfyui
  - denoise
  - dpmpp
  - grayscale
  - karras
  - kotaoue
  - LoRA
  - ohyeah
  - optimised
  - pycache
  - rembg
  - safetensors
  - SDXL
  - Toon
ignoreWords: []
import: []
