version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Achacha
  - ckpt
  - comfyui
  - controlnet
  - denoise
  - dpmpp
  - grayscale
  - karras
  - kawaii
  - kotaoue
  - LoRA
  - ohyeah
  - optimised
  - pycache
  - rembg
  - rocknroll
  - safetensors
  - SDXL
  - Toon
  - xinsir
ignoreWords: []
import: []
